# 最終極簡版 render.yaml

databases:
  - name: laravel-db
    plan: free

services:
  - type: web
    name: laravel-app
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    # buildCommand 已被移除，所有邏輯都在 start.sh 中
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://laravel-app.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_URL
        fromDatabase:
          name: laravel-db
          property: connectionString