# render.yaml

databases:
  - name: laravel-db
    plan: free

services:
  - type: web
    name: laravel-app
    runtime: php      # 確認這一行
    phpVersion: '8.2'  # <<< 新增這一行來指定版本
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate --force
      php artisan migrate --force
    startCommand: php artisan serve --host=0.0.0.0 --port=${PORT}
    envVars:
      - key: APP_URL
        value: https://laravel-app.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        fromDatabase:
          name: laravel-db
          property: connectionString