# render.yaml (最終修正版 v2)

databases:
  - name: laravel-db
    plan: free

services:
  - type: web
    name: laravel-app
    runtime: php      # <<< 修正 #1: 從 env: php 改為 runtime: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate --force
      php artisan migrate --force
    startCommand: php artisan serve --host=0.0.0.0 --port=${PORT}
    envVars:
      - key: APP_URL
        # 請記得將 laravel-app 換成您上面 services 的 name
        value: https://laravel-app.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        fromDatabase:
          name: laravel-db
          property: connectionString # <<< 修正 #2: 從 internalDatabaseUrl 改為 connectionString